name: Run Build Tests
on:
  push:
  workflow_dispatch:

jobs:
  build_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Build Tools
        run: |
          python -m pip install build wheel
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt install python3-dev swig libssl-dev libfann-dev portaudio19-dev libpulse-dev
      - name: Build Source Packages
        run: |
          python setup.py sdist
      - name: Build Distribution Packages
        run: |
          python setup.py sdist bdist_wheel
      - name: Install repo
        run: |
          pip install .
