name: OPM Plugin Check

on:
  pull_request:
    branches: [dev, master, main]
  workflow_dispatch:

jobs:
  opm_check:
    uses: OpenVoiceOS/gh-automations/.github/workflows/opm-check.yml@dev
    secrets: inherit
    with:
      python_version: '3.11'
      plugin_type: 'auto'
      entry_point: ''
      opm_require_found: true
      opm_validate_interface: true
      opm_test_import: true
      opm_perf_threshold_ms: 500
      opm_min_version: '2.2.3a1'
      opm_max_version: '3.0.0'
